# Generated by Django 3.1.5 on 2021-01-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Contact', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Event_Name', models.CharField(max_length=100)),
                ('Type_O_Reg', models.CharField(max_length=50)),
                ('No_Of_Participant', models.IntegerField()),
            ],
        ),
    ]
