# Generated by Django 3.1.5 on 2021-01-06 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Participant_Registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='Contact',
            new_name='Contact_No',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='Type_O_Reg',
            new_name='Type_Of_Registration',
        ),
    ]
