# Generated by Django 3.1.5 on 2021-01-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_Registartion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Password',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
