# Generated by Django 3.1.5 on 2021-01-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_Registartion', '0002_event_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Status',
            field=models.CharField(default='Coming Soon', max_length=50),
            preserve_default=False,
        ),
    ]
